export default {
    home: '/',
    contactUs: '/contact-us',
    signIn: '/sign-in',
    signUp: '/sign-up',
    otp: '/otp',
    emailVerifyLink: '/emailAddress/verify',
    forgotPassword: '/forgot-password',
    resetPassword: '/resetPassword',
    resetLinkVerify: '/reset-password/verify',

    dashboard: '/',
    allProject: '/allProjects',
    addProject: '/addProject',
    taskList: '/task/list',
    taskBoard: '/task/board',
    taskCalendar: '/task/calendar',
    teams: '/teams',
    analaytics: '/analytics',
    notifications: '/notifications',
    subscription: '/subscription',
    settings: '/settings',
    support: '/support',
    profile: '/profile',
    logout: '/logout',
}
